//
//  PasswordGeneratorPresenter.swift
//  DGPPrivateData
//
//  Created by Daniel Gallego Peralta on 8/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PasswordGeneratorPresentationLogic {
    func presentPassword(response: PasswordGeneratorScene.Show.Response)
    func presentCopy(response: PasswordGeneratorScene.Copy.Response)
}

class PasswordGeneratorPresenter: PasswordGeneratorPresentationLogic {
    weak var viewController: PasswordGeneratorDisplayLogic?
    
    func presentPassword(response: PasswordGeneratorScene.Show.Response) {
        let viewModel = PasswordGeneratorScene.Show.ViewModel(password: response.password)
        viewController?.displayPassword(viewModel: viewModel)
    }
    
    func presentCopy(response: PasswordGeneratorScene.Copy.Response) {
        let message = NSLocalizedString("Copy to clipboard", comment: "message when copy text to clipboard success")
        viewController?.displayToast(with: message)
    }
}
