//
//  PasswordGeneratorInteractor.swift
//  DGPPrivateData
//
//  Created by Daniel Gallego Peralta on 8/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PasswordGeneratorBusinessLogic {
    func doLoadPassword(request: PasswordGeneratorScene.Show.Request)
    func doGeneratePassword(request: PasswordGeneratorScene.New.Request)
    func doCopyPassword(request: PasswordGeneratorScene.Copy.Request)
    func doPasswordEditing(request: PasswordGeneratorScene.UpdateText.Request)
    func doApplyChanges(request: PasswordGeneratorScene.ApplyChanges.Request)
    var password: String { get set }
    var tableViewModel: PasswordGeneratorScene.PasswordGeneratorViewModel { get }
}

protocol PasswordGeneratorDataStore {
    var password: String { get set }
    var tableViewModel: PasswordGeneratorScene.PasswordGeneratorViewModel { get }
    var passwordGenerator: PasswordGenerator? { get set }
    var delegate: PasswordGeneratorDelegate? { get set }
}

class PasswordGeneratorInteractor: PasswordGeneratorBusinessLogic, PasswordGeneratorDataStore {
    var presenter: PasswordGeneratorPresentationLogic?
    var worker: PasswordGeneratorWorker?
    
    let tableViewModel = PasswordGeneratorScene.PasswordGeneratorViewModel()
    var passwordGenerator: PasswordGenerator? = nil
    var delegate: PasswordGeneratorDelegate?
    
    var password: String = ""
    
    func doLoadPassword(request: PasswordGeneratorScene.Show.Request) {
        let response = PasswordGeneratorScene.Show.Response(password: password)
        presenter?.presentPassword(response: response)
    }
    
    func doGeneratePassword(request: PasswordGeneratorScene.New.Request) {
        passwordGenerator?.setConfig(request.config)
        password = PasswordManager.shared.generatePassword()
        let response = PasswordGeneratorScene.Show.Response(password: password)
        presenter?.presentPassword(response: response)
    }
    
    func doCopyPassword(request: PasswordGeneratorScene.Copy.Request) {
        UIPasteboard.general.string = request.text
        let response = PasswordGeneratorScene.Copy.Response()
        presenter?.presentCopy(response: response)
    }
    
    func doPasswordEditing(request: PasswordGeneratorScene.UpdateText.Request){
        self.password = request.text
    }
    
    func doApplyChanges(request: PasswordGeneratorScene.ApplyChanges.Request) {
        self.delegate?.passwordGenerator(didUpdatePassword: self.password)
    }
    
}
