//
//  FilterWorker.swift
//  DGPPrivateData
//
//  Created by Daniel Gallego Peralta on 13/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FilterWorker {
    var dataStore: StoreDataSource
    
    init(dataStore: StoreDataSource) {
        self.dataStore = dataStore
    }
    
    func doLoadFilters() -> [Filter] {
        let filterList = dataStore.filterList
        
        if filterList.isNotEmpty {
            return filterList
        }
        
        var filters: [Filter] = [Filter(title: "Favorites",
                              icon: "default_icon",
                              state: true)]
        filters.append(contentsOf: ManagerMasterCoreData.shared.getAllCategories().map { category in
            return Filter(title: category.name, icon: category.icon, state: true)
        })
        
        dataStore.filterList = filters
        return filters
    }
    
    func saveFilters(filter: [Filter]) {
        dataStore.filterList = filter
    }
}
