//
//  FilterModels.swift
//  DGPPrivateData
//
//  Created by Daniel Gallego Peralta on 13/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum FilterScene {
    // MARK: Use cases
    
    enum Load {
        struct Request {
        }
        struct Response {
            let filters: [Filter]
        }
        struct ViewModel {
            var cells: [FilterCellViewModel] = []
            init(filters: [Filter]) {
                filters.forEach {
                    cells.append(FilterCellViewModel(title: $0.title, icon: $0.icon, state: $0.state))
                }
            }
        }
    }
    
    enum ToggleFilter {
        struct Request {
            let index: Int
        }
    }
}

struct FilterCellViewModel {
    let title: String
    let icon: String
    let state: Bool
}

class Filter: Codable {
    let title: String
    let icon: String
    var state: Bool
    
    init(title: String, icon: String, state: Bool) {
        self.title = title
        self.icon = icon
        self.state = state
    }
}

struct FilterSavedList: Codable {
    var filters: [Filter]
}

