//
//  FilterWorker.swift
//  DGPPrivateData
//
//  Created by Daniel Gallego Peralta on 13/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FilterWorker {
    var dataStore: PreferencesService
    
    init(dataStore: PreferencesService) {
        self.dataStore = dataStore
    }
    
    func doLoadFilters() -> (categories: [Filter], orders: [Filter]) {
        var filterList = dataStore.filterList
        
        if filterList.isEmpty {
            filterList = [Filter(title: Filter.favoriteFilterName,
                                 icon: Filter.favoriteFilterIcon,
                                  state: true)]
            filterList.append(contentsOf: CoreDataRepositoryService.shared.getAllCategories().map { category in
                return Filter(title: category.name, icon: category.icon, state: true)
            })
            
            dataStore.filterList = filterList
        }
        
        var orderList = dataStore.orderList
        
        if orderList.isEmpty {
            orderList = [
                Filter(title: Filter.groupByCategories, icon: "", state: true),
                Filter(title: Filter.alphabetically, icon: "", state: false),
            ]
            
            dataStore.orderList = orderList
        }
        
        
        return (filterList, orderList)
    }
    
    func saveFilters(filter: [Filter]) {
        dataStore.filterList = filter
    }
    
    func saveOrderFilters(filters: [Filter]) {
        dataStore.orderList = filters
    }
}
