//
//  FilterPresenter.swift
//  DGPPrivateData
//
//  Created by Daniel Gallego Peralta on 13/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FilterPresentationLogic {
    func presentFilters(response: FilterScene.Load.Response)
}

class FilterPresenter: FilterPresentationLogic {
    weak var viewController: FilterDisplayLogic?
    
    // MARK: Do something
    
    func presentFilters(response: FilterScene.Load.Response) {
        let viewModel = FilterScene.Load.ViewModel(categoryFilters: response.categoryFilters, orderFilters: response.orderFilters)
        viewController?.displayFilters(viewModel: viewModel)
    }
}
