//
//  AuthenticationPresenter.swift
//  DGPPrivateData
//
//  Created by Daniel Gallego Peralta on 5/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
/*
protocol AuthenticationPresentationLogic {
    func presentLogin(response: AuthenticationScene.Login.Response)
    func presentError(error: AuthenticationScene.AuthenticationError)
}

class AuthenticationPresenter: AuthenticationPresentationLogic {
    weak var viewController: AuthenticationDisplayLogic?
    
    // MARK: Do something
    
    func presentLogin(response: AuthenticationScene.Login.Response) {
        let viewModel = AuthenticationScene.Login.ViewModel()
        DispatchQueue.main.async {
            self.viewController?.displayLoginSuccess(viewModel: viewModel)
        }
    }
    
    func presentError(error: AuthenticationScene.AuthenticationError) {
        let description: String
        switch error {
        case .noDevice(let msg):
            description = msg
        case .failedAuth(let msg):
            description = msg
        }
        let viewModel = ErrorViewModel(msg: description)
        DispatchQueue.main.async {
            self.viewController?.displayError(viewModel: viewModel)
        }
    }
}
*/
