//
//  AuthenticationModels.swift
//  DGPPrivateData
//
//  Created by Daniel Gallego Peralta on 5/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AuthenticationScene {
    // MARK: Use cases
    enum AuthenticationState {
        case loggenIn
        case loggedOut
    }
    
    enum AuthenticationError: Error {
        case noDevice(String)
        case failedAuth(String)
    }
    
    enum Login {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
}
