//
//  ListEntryModels.swift
//  DGPPrivateData
//
//  Created by Daniel Gallego Peralta on 4/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListEntryScene {
    // MARK: Use cases
    
    enum Load {
        struct Request {
        }
        struct Response {
            let entries : [Entry]
            let isGroupedCategories: Bool
        }
        struct ViewModel {
            let sections: [ListEntrySection]
            let displaySections: Bool
        }
    }
    
    enum FilterBy {
        struct Request {
            let text: String
        }
        struct Response {
            let entrys : [Entry]
        }
        struct ViewModel {
            let cellsModel: [ListEntryCellViewModel]
        }
    }
}

struct ListEntrySection {
    let name: String
    let icon: String
    var cellsModel: [ListEntryCellViewModel]
}
