//
//  ListEntryWorker.swift
//  DGPPrivateData
//
//  Created by Daniel Gallego Peralta on 4/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListEntryWorker {
    
    var dataStore: StoreDataSource
    var masterDataSource: MasterDataSource
    
    init(dataStore: StoreDataSource, masterDataSource: MasterDataSource) {
        self.dataStore = dataStore
        self.masterDataSource = masterDataSource
    }
    
    func fetchEntrys(applyFilters: Bool, completionHandler: ([Entry]) -> Void ) {
        
        let filtersName = dataStore.filterList.filter {
            $0.state
        }.map {
            return $0.title
        }
        let categoriesFilter = FilterType.categories(filtersName)
        
        let order = dataStore.orderList.filter { $0.title == "Alphabetically" }.first
        
        let orderFilter = FilterType.order(order?.state == true ? .alphabetically : .default)
        
        completionHandler(
            masterDataSource.getAllEntries(filters: [categoriesFilter, orderFilter]))
    }
}
