//
//  ListEntryRouter.swift
//  DGPPrivateData
//
//  Created by Daniel Gallego Peralta on 4/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListEntryRoutingLogic {
    func routeToAddEntry()
    func routeToEditEntry()
}

protocol ListEntryDataPassing {
    var dataStore: ListEntryDataStore? { get }
}

class ListEntryRouter: NSObject, ListEntryRoutingLogic, ListEntryDataPassing {
    weak var viewController: ListEntryViewController?
    var dataStore: ListEntryDataStore?
    
    // MARK: Routing
    
    func routeToAddEntry() {
        let destinationVC = AddEditEntryViewController.instantiate()
        navigateToAddEntry(source: viewController!, destination: destinationVC)
        
    }
    
    func routeToEditEntry() {
        let destinationVC = AddEditEntryViewController.instantiate()
        var destinationDS = destinationVC.router!.dataStore!
        passDataToEdit(source: dataStore!, destination: &destinationDS)
        navigateToAddEntry(source: viewController!, destination: destinationVC)
    }
    
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    
    func navigateToAddEntry(source: ListEntryViewController, destination: AddEditEntryViewController)
    {
      source.show(destination, sender: nil)
    }
    
     //MARK: Passing data
    
    func passDataToEdit(source: ListEntryDataStore, destination: inout AddEditEntryDataStore) {
        let selectedIndex = viewController!.selectedRow
        destination.entryToEdit = source.entries[selectedIndex!]
    }
}
