//
//  ListEntryWorker.swift
//  DGPPrivateData
//
//  Created by Daniel Gallego Peralta on 4/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListEntryWorker {
    
    var dataStore: StoreDataSource
    
    init(dataStore: StoreDataSource) {
        self.dataStore = dataStore
    }
    
    func fetchEntrys(applyFilters: Bool, completionHandler: ([Entry]) -> Void ) {
        let filtersName = dataStore.filterList.filter {
            $0.state
        }.map {
            return $0.title
        }
        
        ManagerMasterCoreData.shared.getAllEntrys(filterByCategoryName: filtersName) { entrys in
            completionHandler(entrys)
        }
    }
}
