//
//  AddEditEntryWorker.swift
//  DGPPrivateData
//
//  Created by Daniel Gallego Peralta on 4/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class AddEditEntryWorker {
    
    let service: RepositoryService
    
    init(service: RepositoryService) {
        self.service = service
    }
    
    func fetchCategories(completionHandler: @escaping (([Category]) -> Void)) {
        completionHandler(service.getAllCategories())
    }
    
    func save(entry: Entry) -> Result<Entry, Error> {
        do {
            if entry.id == nil {
                return .success(try service.createEntry(entry))
            } else {
                return .success(try service.updateEntry(entry))
            }
        } catch {
            return .failure(error)
        }
        
    }
}
