//
//  AddEditEntryRouter.swift
//  DGPPrivateData
//
//  Created by Daniel Gallego Peralta on 4/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddEditEntryRoutingLogic {
    func routeToListEntry()
    func routeToPasswordGenerator()
}

protocol AddEditEntryDataPassing {
    var dataStore: AddEditEntryDataStore? { get }
}

class AddEditEntryRouter: NSObject, AddEditEntryRoutingLogic, AddEditEntryDataPassing {
    weak var viewController: AddEditEntryViewController?
    var dataStore: AddEditEntryDataStore?
    
    // MARK: Routing

    func routeToListEntry() {
        viewController?.navigationController?.popViewController(animated: true)
    }
    
    func routeToPasswordGenerator() {
        let destinationVC = PasswordGeneratorViewController.makePasswordGenerator(initialPassword: dataStore!.password, delegate: self.viewController)
        viewController?.showDetailViewController(destinationVC, sender: nil)
    }
    
    // MARK: Navigation
    
    func navigateToListEntry(source: AddEditEntryViewController, destination: ListEntryViewController) {
        source.navigationController?.popViewController(animated: true)
    }
    
}
