//
//  AddEditEntryRouter.swift
//  DGPPrivateData
//
//  Created by Daniel Gallego Peralta on 4/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddEditEntryRoutingLogic {
    func routeToListEntry()
}

protocol AddEditEntryDataPassing {
    var dataStore: AddEditEntryDataStore? { get }
}

class AddEditEntryRouter: NSObject, AddEditEntryRoutingLogic, AddEditEntryDataPassing {
    weak var viewController: AddEditEntryViewController?
    var dataStore: AddEditEntryDataStore?
    

    
    // MARK: Routing

    func routeToListEntry() {
        let index = viewController!.navigationController!.viewControllers.count - 2
        let destinationVC = viewController?.navigationController?.viewControllers[index] as! ListEntryViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToListEntry(source: dataStore!, destination: &destinationDS)
        navigateToListEntry(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    
    func navigateToListEntry(source: AddEditEntryViewController, destination: ListEntryViewController) {
        source.navigationController?.popViewController(animated: true)
    }
    
     //MARK: Passing data
    
    func passDataToListEntry(source: AddEditEntryDataStore, destination: inout ListEntryDataStore) {
      
    }
}
