//
//  AddEditEntryInteractor.swift
//  DGPPrivateData
//
//  Created by Daniel Gallego Peralta on 4/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddEditEntryBusinessLogic {
    func loadInitialData(request: AddEditEntryScene.Load.Request)
    func saveEntry(request: AddEditEntryScene.Save.Request)
    func updateEntry(request: AddEditEntryScene.Save.Request)
    func showEntryToEdit(request: AddEditEntryScene.Edit.Request)
    func updatedCategory(request: AddEditEntryScene.UpdateCategory.Request)
    func updatePassword(request: AddEditEntryScene.UpdatePassword.Request)
    func updateNewPassword(request: AddEditEntryScene.UpdateNewPassword.Request)
    func copyText(request: AddEditEntryScene.Copy.Request)
    func toggleIsFavorite(request: AddEditEntryScene.UpdateFavorite.Request)
    var entryToEdit: Entry? { get set }
    var title: String { get set }
    var username: String { get set }
    var password: String { get set }
    var notes: String { get set }
    var isValid: Bool { get }
    var selectedIndex: Int { get set }
}

protocol AddEditEntryDataStore {
    var entryToEdit: Entry? { get set }
    var title: String { get set }
    var username: String { get set }
    var password: String { get set }
    var notes: String { get set }
    var isFavorite: Bool { get set }
    var isValid: Bool { get }
    var selectedIndex: Int { get set }
}

class AddEditEntryInteractor: AddEditEntryBusinessLogic, AddEditEntryDataStore {
    var presenter: AddEditEntryPresentationLogic?
    var worker: AddEditEntryWorker?
    
    var entryToEdit: Entry?
    var title: String = ""
    var username: String = ""
    var password: String = ""
    var notes: String = ""
    var isFavorite: Bool = false
    
    var categories = [Category]()
    let masterService: MasterDataSource
    var selectedIndex: Int = 0
    
    init(service: MasterDataSource = ManagerMasterCoreData.shared) {
        self.masterService = service
        worker = AddEditEntryWorker(service: service)
    }
    
    // MARK: Input
    
    func loadInitialData(request: AddEditEntryScene.Load.Request) {
        worker?.fetchCategories { [weak self] categories in
            self?.categories = categories
            self?.selectedIndex = ManagerMasterCoreData.defaultCategoryIndex
            let response = AddEditEntryScene.Load.Response(categories: categories)
            self?.presenter?.presentInitialData(response: response)
        }
    }
    
    func saveEntry(request: AddEditEntryScene.Save.Request) {
        let category = categories[selectedIndex]
        
        worker?.createEntry(with: request.entryFormFields, category: category, completionHandler: { [weak self] result in
            switch result {
            case .success(let entry):
                let response = AddEditEntryScene.Save.Response(entry: entry)
                self?.presenter?.presentCreatedEntry(response: response)
            case .failure(let error):
                self?.presenter?.presentError(error: error)
            }
        })
    }
    
    func updateEntry(request: AddEditEntryScene.Save.Request) {
        guard let entryToEdit = entryToEdit else {
            print("no entity edit to save")
            self.presenter?.presentError(error: AddEditEntryScene.AddEditError.entityNotPresent)
            return
        }
        
        let category = categories[selectedIndex]
        let entity = buildEntryFromFields(entity: entryToEdit, fields: request.entryFormFields, category: category)
        worker?.editEntry(entry: entity) { [weak self] result in
            switch result {
            case .success(let entity):
                let response = AddEditEntryScene.Save.Response(entry: entity)
                self?.presenter?.presentUpdatedEntry(response: response)
            case .failure(let error):
                self?.presenter?.presentError(error: error)
            }
        }
        
        
    }
    
    func showEntryToEdit(request: AddEditEntryScene.Edit.Request) {
        //fixme
//        if let entryToEdit = entryToEdit {
//           let category = entryToEdit.category
//            selectedIndex = categories.firstIndex(of: category) ?? 0
//            isFavorite = entryToEdit.favorite
//            password = entryToEdit.password ?? ""
//            let response = AddEditEntryScene.Edit.Response(entry: entryToEdit)
//            self.presenter?.presentEntryToEdit(response: response)
//
//        }
    }
    
    func updatedCategory(request: AddEditEntryScene.UpdateCategory.Request) {
        let selectedCategory = categories[selectedIndex]
        let response = AddEditEntryScene.UpdateCategory.Response(category: selectedCategory)
        self.presenter?.presentSelectedCategory(response: response)
    }
    
    func updatePassword(request: AddEditEntryScene.UpdatePassword.Request) {
        let response = AddEditEntryScene.UpdatePassword.Response(password: password)
        presenter?.presentUpdatePassword(response: response)
    }
    
    func updateNewPassword(request: AddEditEntryScene.UpdateNewPassword.Request) {
        self.password = request.password
    }
    
    func toggleIsFavorite(request: AddEditEntryScene.UpdateFavorite.Request) {
        self.isFavorite.toggle()
        let response = AddEditEntryScene.UpdateFavorite.Response(isfavorite: self.isFavorite)
        presenter?.presentUpdateFavorite(response: response)
    }
    
    func copyText(request: AddEditEntryScene.Copy.Request) {
        UIPasteboard.general.string = request.text
        presenter?.presentCopySuccess(response: AddEditEntryScene.Copy.Response())
    }
    
    //MARK: - Utils
    
    private func buildEntryFromFields(entity: Entry, fields: AddEditEntryScene.EntryFormFields, category: Category) -> Entry {
        let entry = Entry(
            title: fields.title,
            username: fields.username,
            password: fields.password,
            url: "",
            notes: fields.notes,
            favorite: fields.favorite,
            category: category
        )
        
        return entry
    }
    
    var isValid:  Bool {
        return !title.isEmpty || !username.isEmpty || !password.isEmpty || !notes.isEmpty
    }
    
    
}
